'use client'
import {useCallback,useEffect,useState,type CSSProperties} from 'react'
import Link from 'next/link'
import {TASKS,STEP_LABELS,PROFILE_FIELDS,FORM_LABELS,FORM_FIELDS,activeTasks,blockedBy,nextTask,dueDate,defaultDraft,emptyLine,validateDraft,type Workflow,type FormKind,type Draft,type Step} from '@/lib/proiect-workflow'
const box:CSSProperties={padding:20,border:'1px solid var(--border)',borderRadius:'var(--r-lg)',background:'var(--surface)'}
const input:CSSProperties={width:'100%',padding:'9px 10px',border:'1px solid var(--border)',borderRadius:'var(--r-sm)',background:'var(--c-0d0d0d)',color:'var(--text-primary)',fontSize:'var(--fs-md)'}
const button:CSSProperties={padding:'0 12px',height:32,display:'inline-flex',alignItems:'center',gap:6,borderRadius:'var(--r-md)',border:'1px solid var(--border-strong)',background:'var(--surface)',color:'var(--text-primary)',cursor:'pointer',fontSize:'var(--fs-md)',fontWeight:550}
const tabStyle=(active:boolean):CSSProperties=>active?{...button,background:'var(--accent-soft)',borderColor:'var(--accent)',color:'var(--accent)'}:button
const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}
const hint:CSSProperties={fontSize:'var(--fs-sm)',color:'var(--text-muted)',lineHeight:1.6}
const common=new Set(['achizitie','tip','furnizor','adresa_furnizor','identificare_furnizor','reprezentant_furnizor','referinta'])
async function response(res:Response){const data=await res.json();if(!res.ok)throw new Error(data.error||'Operația a eșuat');return data}
function errorText(e:unknown){return e instanceof Error?e.message:'Operația a eșuat'}
export default function ProiectWorkflow({firmaId,lunaId,luna,firmaSlug='proiect-ab-textile',purchaseId,compact=false,initialForm=false}:{firmaId:string;lunaId?:string;luna?:string;firmaSlug?:string;purchaseId?:string;compact?:boolean;initialForm?:boolean}){
 const scope=purchaseId?`purchase-${purchaseId}`:`month-${lunaId}`
 const [state,setState]=useState<Workflow|null>(null),[settings,setSettings]=useState<Workflow|null>(null)
 const [tab,setTab]=useState<'rutina'|'formulare'|'setari'>(purchaseId||initialForm?'formulare':'rutina')
 const [kind,setKind]=useState<FormKind>(purchaseId?'oferta':'raport')
 const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[settingsDirty,setSettingsDirty]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const url=`/api/proiect-workflow?firmaId=${encodeURIComponent(firmaId)}&scope=${encodeURIComponent(scope)}`
 const load=useCallback(async()=>{setError('');try{const data=await response(await fetch(url,{cache:'no-store'}));setState(data.state);setDirty(false)}catch(e){setError(errorText(e))}},[url])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!dirty&&!settingsDirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,settingsDirty])
 function edit(next:Workflow){setState(next);setDirty(true);setMessage('')}
 async function save(next=state){if(!next)return null;const data=await response(await fetch('/api/proiect-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope,state:next})}));setState(data.state);setDirty(false);if(data.warning)setError(data.warning);return data.state as Workflow}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function openSettings(){if(settings){setTab('setari');return}await run(async()=>{const data=await response(await fetch(`/api/proiect-workflow?firmaId=${firmaId}&scope=settings`,{cache:'no-store'}));setSettings(data.state);setTab('setari')})}
 function assetUrl(id:string){return `/api/proiect-workflow/document?firmaId=${firmaId}&scope=${scope}&id=${id}`}
 async function upload(file:File,task:string){await run(async()=>{if(file.size>4*1024*1024)throw new Error('Fișierul depășește limita de 4 MB.');const saved=await save();if(!saved)return;const fd=new FormData();fd.set('firmaId',firmaId);fd.set('scope',scope);fd.set('version',String(saved.version));fd.set('task',task);fd.set('file',file);const data=await response(await fetch('/api/proiect-workflow/document',{method:'POST',body:fd}));setState(data.state);setMessage('Document salvat. Confirmă separat verificarea, semnarea sau trimiterea.')})}
 const selected=state?.forms[kind]||defaultDraft(kind,luna)
 function changeDraft(draft:Draft){if(!state)return;const forms={...state.forms,[kind]:draft};if(purchaseId){const shared=Object.fromEntries(Object.entries(draft.fields).filter(([key])=>common.has(key)));for(const k of ['oferta','nota','receptie'] as FormKind[]){if(k===kind)continue;const other=forms[k]||defaultDraft(k);forms[k]={fields:{...other.fields,...shared},lines:other.lines}}}edit({...state,forms})}
 const err=error&&<div role="alert" style={{...box,borderColor:'var(--danger)',color:'var(--danger)'}}>{error} <button style={button} onClick={()=>{if(!dirty||confirm('Reîncarci și renunți la modificările nesalvate?'))void load()}}>Reîncarcă</button></div>
 if(!state)return <div style={box}>{err||'Se încarcă rutina proiectului…'}</div>
 const workflow=state
 const month=luna||'',next=month?nextTask(state,month):null,visible=month?activeTasks(state,month):[]
 const complete=visible.filter(t=>['acceptat','neaplicabil'].includes(state.tasks[t.key]?.status)).length
 const sent=visible.filter(t=>state.tasks[t.key]?.status==='trimis').length
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Bucharest'}).format(new Date())
 const overdue=visible.filter(t=>state.tasks[t.key]?.due&&state.tasks[t.key].due!<today&&!['trimis','acceptat','neaplicabil'].includes(state.tasks[t.key].status)).length
 const salaryKeys=new Set(['stat','pontaj','reges','centralizator','creditare','salarii','extras','registru'])
 const salaryOrder=['stat','pontaj','reges','centralizator','creditare','extras','registru','salarii']
 const salaryTasks=visible.filter(t=>salaryKeys.has(t.key)).sort((a,b)=>salaryOrder.indexOf(a.key)-salaryOrder.indexOf(b.key))
 const taskDone=(key:string)=>['trimis','acceptat','neaplicabil'].includes(state.tasks[key]?.status)
 const salaryDue=salaryTasks.filter(t=>!taskDone(t.key)).map(t=>state.tasks[t.key]?.due||'9999').sort()[0]||salaryTasks.map(t=>state.tasks[t.key]?.due||'9999').sort()[0]||'9999'
 const displayRows=[
  ...visible.filter(t=>!salaryKeys.has(t.key)).map(t=>({task:t as typeof TASKS[number]|null,due:state.tasks[t.key]?.due||'9999',done:taskDone(t.key)?1:0})),
  ...(salaryTasks.length?[{task:null as typeof TASKS[number]|null,due:salaryDue,done:salaryTasks.every(t=>taskDone(t.key))?1:0}]:[])
 ].sort((a,b)=>a.done-b.done||a.due.localeCompare(b.due))
 function taskFields(t:typeof TASKS[number]){
  const row=workflow.tasks[t.key];if(!row)return null
  const blocked=blockedBy(t.key,workflow),assets=workflow.assets.filter(a=>a.task===t.key)
  return <div style={{marginTop:14}}>
 <div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><h3 style={{fontWeight:650,fontSize:'var(--fs-lg)'}}>{t.key==='salarii'?'Confirmarea plății salariilor și contribuțiilor':t.title}</h3><p style={hint}>{t.source}</p></div><label style={hint}>Termen pentru această lună<input aria-label={`Termen ${t.title}`} type="date" value={row.due||''} style={input} onChange={e=>edit({...workflow,tasks:{...workflow.tasks,[t.key]:{...row,due:e.target.value||null}}})}/></label></div>
 <p style={{...hint,margin:'10px 0'}}>{t.action}</p>
 {blocked.length>0&&<p style={{...hint,color:'var(--danger)'}}>Mai întâi: {blocked.join(', ')}</p>}
 <div style={grid}><label style={hint}>Stare confirmată de tine<select style={input} value={row.status} aria-label={`Stare ${t.title}`} onChange={e=>edit({...workflow,tasks:{...workflow.tasks,[t.key]:{...row,status:e.target.value as Step}}})}>{Object.entries(STEP_LABELS).filter(([key])=>['creditare','salarii','chirie'].includes(t.key)||!['initiat','avizat','executat'].includes(key)).map(([key,label])=><option key={key} value={key} disabled={blocked.length>0&&['semnat','trimis','acceptat','initiat','avizat','executat'].includes(key)}>{label}</option>)}</select></label><label style={hint}>Observații / referință confirmare<input style={input} value={row.note} onChange={e=>edit({...workflow,tasks:{...workflow.tasks,[t.key]:{...row,note:e.target.value}}})}/></label></div>
 <div style={{display:'flex',gap:12,marginTop:12,alignItems:'center',flexWrap:'wrap'}}><label style={{...button,cursor:'pointer'}}>+ Adaugă document (max. 4 MB)<input type="file" accept=".pdf,.docx,.jpg,.jpeg,.png" style={{display:'none'}} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void upload(f,t.key)}}/></label>{t.key==='raport'&&<button style={button} onClick={()=>{setKind('raport');setTab('formulare')}}>Completează raportul →</button>}{assets.map(a=><a key={a.id} style={{fontSize:'var(--fs-sm)',color:'var(--accent)'}} href={assetUrl(a.id)}>{a.name} ↓</a>)}</div>
 </div>
 }
 if(compact)return <section style={{...box,marginBottom:24,borderLeft:'4px solid var(--accent)'}}><div style={hint}>RUTINA PROIECTULUI · {complete}/{visible.length} încheiate · {sent} trimise · {overdue} restante</div><h2 style={{fontSize:18,fontWeight:650,margin:'7px 0'}}>{next?`Următorul pas: ${next.title}`:'Documentele sunt trimise sau încheiate'}</h2><p style={hint}>{next?.action||'Verifică răspunsurile și marchează acceptările primite.'}</p><Link href={`/${firmaSlug}/${luna}/obligatii-recurente`} style={{color:'var(--accent)',fontSize:'var(--fs-md)',fontWeight:600}}>Deschide rutina lunii →</Link></section>
 return <section style={{display:'grid',gap:16}}>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}>
 {!purchaseId&&<button style={tabStyle(tab==='rutina')} aria-pressed={tab==='rutina'} onClick={()=>setTab('rutina')}>Rutina lunii</button>}
 <button style={tabStyle(tab==='formulare')} aria-pressed={tab==='formulare'} onClick={()=>setTab('formulare')}>Formulare și versiuni</button>
 <button style={tabStyle(tab==='setari')} aria-pressed={tab==='setari'} disabled={busy} onClick={()=>void openSettings()}>Date permanente și termene</button>
 <span role="status" style={{...hint,marginLeft:'auto'}}>{busy?'Se salvează…':dirty||settingsDirty?'Modificări nesalvate':state.updatedAt?`Salvat · v${state.version}`:''}</span>
 {tab!=='setari'&&<button style={{...button,background:'var(--accent)',color:'#fff'}} disabled={busy||!dirty} onClick={()=>void run(async()=>{await save();setMessage('Modificările au fost salvate.')})}>Salvează modificările</button>}
 </div>
 {err}{message&&<div role="status" style={{...hint,color:'var(--success)'}}>{message}</div>}
 <fieldset disabled={busy} style={{border:0,padding:0,minWidth:0,display:'grid',gap:16}}>
 {tab==='rutina'&&<>
 <div style={{...box,borderLeft:'4px solid var(--accent)'}}><div style={hint}>{complete}/{visible.length} încheiate · {sent} trimise, în așteptarea acceptării · {overdue} restante</div><h2 style={{fontSize:20,fontWeight:650,margin:'8px 0'}}>{next?`Următorul pas: ${next.title}`:'Totul este trimis sau încheiat'}</h2><p style={hint}>{next?.action||'Confirmă acceptările primite. Trimiterea nu confirmă acceptarea.'}</p>{next&&<a href={salaryKeys.has(next.key)?'#rutina-salarii':'#rutina-'+next.key} style={{fontSize:'var(--fs-md)',color:'var(--accent)'}}>Mergi la pas →</a>}</div>
 <p style={hint}>Documentele se referă la luna anterioară lunii de lucru. Termenele sunt orientative și pot fi corectate. Data încărcării nu confirmă semnarea, trimiterea sau executarea unei plăți.</p>
 {displayRows.map(item=>item.task?<details id={'rutina-'+item.task.key} key={item.task.key} style={box} open={next?.key===item.task.key||undefined}><summary style={{cursor:'pointer',fontSize:'var(--fs-base)',fontWeight:650}}>{item.task.title} <span style={{...hint,fontWeight:400}}> · {STEP_LABELS[state.tasks[item.task.key].status]} · {state.tasks[item.task.key].due||'Termen de stabilit'}</span></summary>{taskFields(item.task)}</details>:<details id="rutina-salarii" key="salary-group" style={box} open={!!next&&salaryKeys.has(next.key)||undefined}><summary style={{cursor:'pointer',fontSize:'var(--fs-base)',fontWeight:650}}>Plata salariilor și contribuțiilor <span style={{...hint,fontWeight:400}}> · {salaryTasks.filter(t=>['acceptat','neaplicabil'].includes(state.tasks[t.key]?.status)).length}/{salaryTasks.length} pași încheiați · {salaryDue==='9999'?'Termen de stabilit':salaryDue}</span></summary><p style={{...hint,marginTop:12}}>Documentele și confirmarea plății se gestionează aici, fiecare cu starea, termenul și fișierele sale.</p><div style={{display:'grid',gap:12}}>{salaryTasks.map(t=><section key={t.key} id={t.key==='salarii'?'rutina-salarii-plata':'rutina-'+t.key} style={{padding:'14px 0',borderTop:'1px solid var(--border)'}}><div style={hint}>{STEP_LABELS[state.tasks[t.key].status]} · {state.tasks[t.key].due||'Termen de stabilit'}</div>{taskFields(t)}</section>)}</div></details>)}
 <p style={hint}>Raportarea AJOFM apare în luna anuală configurată (implicit martie). Anexa 7 nu este inclusă. Documentele din vechiul flux rămân în „Documente anterioare”.</p>
 </>}
 {tab==='formulare'&&<>
 <div style={box}><label style={hint}>Alege formularul<select style={{...input,marginTop:5}} value={kind} onChange={e=>setKind(e.target.value as FormKind)}>{Object.entries(FORM_LABELS).filter(([k])=>purchaseId?['oferta','nota','receptie'].includes(k):['raport','restituire'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{selected?.fields._preluat&&<p style={hint}>Câmpuri preluate din {selected.fields._preluat}. Revizuiește activitățile și personalul pentru perioada curentă.</p>}<p style={{...hint,marginTop:10}}>Se generează un document Word editabil, pe modelul original. Fiecare generare păstrează o versiune separată. Verifică datele înainte de semnare. {purchaseId?'Datele comune despre achiziție sunt preluate automat; produsele pot fi copiate între formulare la cerere.':''}</p></div>
 <div style={box}><h3 style={{fontSize:'var(--fs-lg)',fontWeight:650,marginBottom:12}}>Beneficiar — datele acestui dosar</h3><div style={grid}>{Object.entries(PROFILE_FIELDS).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={state.profile[key]||''} onChange={e=>edit({...state,profile:{...state.profile,[key]:e.target.value}})}/></label>)}</div><p style={{...hint,marginTop:8}}>Datele permanente precompletează dosarele noi. Corecțiile de aici afectează doar acest dosar.</p></div>
 <div style={box}><h3 style={{fontSize:'var(--fs-lg)',fontWeight:650,marginBottom:12}}>{FORM_LABELS[kind]}</h3><div style={grid}>{Object.entries(FORM_FIELDS[kind]).map(([key,label])=><label key={key} style={hint}>{label}<textarea rows={['autorizatii','obiective','activitati','constatari','justificare','personal','personal_vulnerabil'].includes(key)?4:2} style={{...input,resize:'vertical'}} value={selected!.fields[key]||''} onChange={e=>changeDraft({...selected!,fields:{...selected!.fields,[key]:e.target.value}})}/></label>)}</div>
 {purchaseId&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{(['oferta','nota','receptie'] as FormKind[]).filter(k=>k!==kind&&state.forms[k]?.lines.length).map(k=><button key={k} style={button} onClick={()=>{if(confirm('Înlocuiești pozițiile acestui formular cu cele din '+FORM_LABELS[k]+'?'))changeDraft({...selected!,lines:structuredClone(state.forms[k].lines)})}}>Preia produse din {FORM_LABELS[k]}</button>)}</div>}
 {['oferta','nota','receptie'].includes(kind)&&<div style={{display:'grid',gap:12,marginTop:20}}><h4 style={{fontSize:'var(--fs-base)',fontWeight:650}}>Produse și servicii — câte o poziție distinctă</h4>{selected!.lines.map((line,index)=><div key={index} style={{...box,padding:12}}><div style={grid}>{Object.entries({supplier:'Furnizor / ofertă',product:'Produs / serviciu',specs:'Specificații tehnice',unit:'UM',qty:'Cantitate',price:'Preț unitar fără TVA',currency:'Monedă',rate:'Curs în lei (1 pentru RON)',source:'Sursă / URL ofertă',date:'Data ofertei'}).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={line[key as keyof typeof line]} onChange={e=>changeDraft({...selected!,lines:selected!.lines.map((x,i)=>i===index?{...x,[key]:e.target.value}:x)})}/></label>)}</div><button style={{...button,marginTop:8}} onClick={()=>changeDraft({...selected!,lines:selected!.lines.filter((_,i)=>i!==index)})}>Elimină poziția {index+1}</button></div>)}<button style={button} onClick={()=>changeDraft({...selected!,lines:[...selected!.lines,emptyLine()]})}>+ Adaugă poziție</button><p style={hint}>Pentru nota de estimare: o poziție pentru fiecare produs din fiecare ofertă. În cerere și recepție păstrează doar produsele necesare; folosește butoanele „Preia produse” pentru a copia lista între formulare.</p></div>}
 <button style={{...button,background:'var(--accent)',color:'#fff',marginTop:18}} onClick={()=>void run(async()=>{const missing=validateDraft(kind,selected!,state.profile);if(missing.length)throw new Error('Completează: '+missing.join('; '));const updated={...state,forms:{...state.forms,[kind]:selected!}};const saved=await save(updated);const data=await response(await fetch('/api/proiect-workflow/document',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope,version:saved!.version,kind})}));setState(data.state);setMessage('Document generat. Îl poți descărca din versiunile de mai jos.')})}>Salvează și generează Word</button>
 </div>
 <div style={box}><h3 style={{fontWeight:650,marginBottom:10}}>Versiuni păstrate — {FORM_LABELS[kind]}</h3>{state.assets.filter(a=>a.task===kind).length===0?<p style={hint}>Nicio versiune încă.</p>:state.assets.filter(a=>a.task===kind).slice().reverse().map(a=><div key={a.id} style={{padding:'8px 0',fontSize:'var(--fs-md)'}}><a style={{color:'var(--accent)'}} href={assetUrl(a.id)}>{a.name} ↓</a><span style={{...hint,marginLeft:10}}>{new Date(a.createdAt).toLocaleString('ro-RO')}</span></div>)}</div>
 </>}
 {tab==='setari'&&settings&&<div style={box}><h3 style={{fontSize:18,fontWeight:650,marginBottom:12}}>Date permanente și reguli pentru dosarele noi</h3><p style={hint}>Modificarea regulilor nu schimbă lunile deja începute. Ziua se calculează în luna de lucru (următoarea perioadei raportate); zilele 29–31 se limitează la ultima zi disponibilă.</p><div style={{...grid,margin:'14px 0'}}>{Object.entries(PROFILE_FIELDS).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={settings.profile[key]||''} onChange={e=>{setSettingsDirty(true);setSettings({...settings,profile:{...settings.profile,[key]:e.target.value}})}}/></label>)}</div>
 {TASKS.map(t=>{const r=settings.rules[t.key];return <div key={t.key} style={{...grid,alignItems:'end',padding:'12px 0',borderTop:'1px solid var(--border)'}}><span style={{fontSize:'var(--fs-md)'}}>{t.title}</span><label style={hint}>Frecvență<select style={input} value={r.frequency} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,frequency:e.target.value as typeof r.frequency}}})}}><option value="monthly">Lunar</option><option value="annual">Anual</option><option value="manual">La cerere, fără termen automat</option></select></label><label style={hint}>Ziua (1–31)<input style={input} type="number" min="1" max="31" value={r.day} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,day:Number(e.target.value)}}})}}/></label><label style={hint}>{r.frequency==='annual'?'Luna din an (1–12)':'Decalaj față de luna de lucru'}<input style={input} type="number" min={r.frequency==='annual'?1:0} max={r.frequency==='annual'?12:2} value={r.frequency==='annual'?r.month:r.offset} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,[r.frequency==='annual'?'month':'offset']:Number(e.target.value)}}})}}/></label></div>})}
 <div style={{display:'flex',gap:10,marginTop:16,flexWrap:'wrap'}}><button style={button} onClick={()=>void run(async()=>{const data=await response(await fetch('/api/proiect-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope:'settings',state:settings})}));setSettings(data.state);setSettingsDirty(false);setMessage('Datele permanente și termenele pentru dosarele noi au fost salvate.')})}>Salvează regulile permanente</button><button style={button} onClick={()=>{edit({...state,profile:{...settings.profile}});setTab('formulare')}}>Preia datele permanente în acest dosar</button>{!purchaseId&&<button style={button} onClick={()=>{if(confirm('Recalculezi toate termenele acestei luni după regulile afișate?')){edit({...state,rules:settings.rules,tasks:Object.fromEntries(Object.entries(state.tasks).map(([key,row])=>[key,{...row,due:dueDate(month,settings.rules[key])}]))});setTab('rutina')}}}>Aplică regulile și acestei luni</button>}</div>
 </div>}
 </fieldset>
 </section>
}
