'use client'
import {useCallback,useEffect,useRef,useState,type CSSProperties} from 'react'
import RutinaLunii from '@/components/proiect/RutinaLunii'
import Link from 'next/link'
import {TASKS,STEP_LABELS,PROFILE_FIELDS,FORM_LABELS,FORM_FIELDS,activeTasks,blockedBy,nextTask,dueDate,defaultDraft,emptyLine,validateDraft,type Workflow,type FormKind,type Draft,type Step} from '@/lib/proiect-workflow'
const box:CSSProperties={padding:20,border:'1px solid var(--border)',borderRadius:'var(--r-lg)',background:'var(--surface)'}
const input:CSSProperties={width:'100%',padding:'9px 11px',border:'1px solid var(--border)',borderRadius:'var(--r-md)',background:'var(--surface-sunken)',color:'var(--text-primary)',fontSize:'var(--fs-md)',marginTop:5,fontFamily:'inherit'}
const button:CSSProperties={padding:'0 12px',height:32,display:'inline-flex',alignItems:'center',gap:6,borderRadius:'var(--r-md)',border:'1px solid var(--border-strong)',background:'var(--surface)',color:'var(--text-primary)',cursor:'pointer',fontSize:'var(--fs-md)',fontWeight:550}
const tabStyle=(active:boolean):CSSProperties=>({...button,height:36,padding:'0 16px',borderRadius:'var(--r-full)',fontWeight:active?700:550,...(active?{background:'var(--accent-solid)',borderColor:'var(--accent-solid)',color:'#fff'}:{background:'var(--surface)',color:'var(--text-secondary)'})})
const grid:CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}
const hint:CSSProperties={fontSize:'var(--fs-sm)',color:'var(--text-secondary)',lineHeight:1.6}
const common=new Set(['achizitie','tip','furnizor','adresa_furnizor','identificare_furnizor','reprezentant_furnizor','referinta'])
async function response(res:Response){const data=await res.json();if(!res.ok)throw new Error(data.error||'Operația a eșuat');return data}
function errorText(e:unknown){return e instanceof Error?e.message:'Operația a eșuat'}
export default function ProiectWorkflow({firmaId,lunaId,luna,firmaSlug='proiect-ab-textile',purchaseId,compact=false,initialForm=false}:{firmaId:string;lunaId?:string;luna?:string;firmaSlug?:string;purchaseId?:string;compact?:boolean;initialForm?:boolean}){
 const scope=purchaseId?`purchase-${purchaseId}`:`month-${lunaId}`
 const [state,setState]=useState<Workflow|null>(null),[settings,setSettings]=useState<Workflow|null>(null)
 const [tab,setTab]=useState<'rutina'|'formulare'|'setari'>(purchaseId||initialForm?'formulare':'rutina')
 const [kind,setKind]=useState<FormKind>(purchaseId?'oferta':'raport')
 const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[settingsDirty,setSettingsDirty]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const url=`/api/proiect-workflow?firmaId=${encodeURIComponent(firmaId)}&scope=${encodeURIComponent(scope)}`
 const load=useCallback(async()=>{setError('');try{const data=await response(await fetch(url,{cache:'no-store'}));setState(data.state);setDirty(false)}catch(e){setError(errorText(e))}},[url])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(!dirty&&!settingsDirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault()};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty,settingsDirty])
 const editSeq=useRef(0),[autoSaving,setAutoSaving]=useState(false)
 function edit(next:Workflow){editSeq.current++;setState(next);setDirty(true);setMessage('')}
 // Salvare automata la ~1,2s dupa ultima modificare (stari, termene, observatii, formulare) - nu se mai
 // pierd modificari uitate nesalvate. Daca s-a mai editat intre timp, pastram editarile locale si
 // preluam doar noua versiune (serverul respinge suprascrierile concurente).
 useEffect(()=>{if(!dirty||!state||busy)return;const seq=editSeq.current;const timer=setTimeout(async()=>{setAutoSaving(true);try{const data=await response(await fetch('/api/proiect-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope,state})}));if(editSeq.current===seq){setState(data.state);setDirty(false)}else setState(prev=>prev?{...prev,version:data.state.version,updatedAt:data.state.updatedAt}:prev);if(data.warning)setError(data.warning)}catch(e){setError(errorText(e))}finally{setAutoSaving(false)}},1200);return()=>clearTimeout(timer)},[state,dirty,busy,firmaId,scope])
 async function save(next=state){if(!next)return null;const data=await response(await fetch('/api/proiect-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope,state:next})}));setState(data.state);setDirty(false);if(data.warning)setError(data.warning);return data.state as Workflow}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function openSettings(){if(settings){setTab('setari');return}await run(async()=>{const data=await response(await fetch(`/api/proiect-workflow?firmaId=${firmaId}&scope=settings`,{cache:'no-store'}));setSettings(data.state);setTab('setari')})}
 function assetUrl(id:string){return `/api/proiect-workflow/document?firmaId=${firmaId}&scope=${scope}&id=${id}`}
 async function upload(file:File,task:string){await run(async()=>{if(file.size>4*1024*1024)throw new Error('Fișierul depășește limita de 4 MB.');const saved=await save();if(!saved)return;const fd=new FormData();fd.set('firmaId',firmaId);fd.set('scope',scope);fd.set('version',String(saved.version));fd.set('task',task);fd.set('file',file);const data=await response(await fetch('/api/proiect-workflow/document',{method:'POST',body:fd}));setState(data.state);setMessage('Document salvat. Confirmă separat verificarea, semnarea sau trimiterea.')})}
 const selected=state?.forms[kind]||defaultDraft(kind,luna)
 function changeDraft(draft:Draft){if(!state)return;const forms={...state.forms,[kind]:draft};if(purchaseId){const shared=Object.fromEntries(Object.entries(draft.fields).filter(([key])=>common.has(key)));for(const k of ['oferta','nota','receptie'] as FormKind[]){if(k===kind)continue;const other=forms[k]||defaultDraft(k);forms[k]={fields:{...other.fields,...shared},lines:other.lines}}}edit({...state,forms})}
 const err=error&&<div role="alert" style={{...box,borderColor:'var(--danger)',color:'var(--danger)'}}>{error} <button style={button} onClick={()=>{if(!dirty||confirm('Reîncarci și renunți la modificările nesalvate?'))void load()}}>Reîncarcă</button></div>
 if(!state)return <div style={box}>{err||'Se încarcă rutina proiectului…'}</div>
 const workflow=state
 const month=luna||'',next=month?nextTask(state,month):null,visible=month?activeTasks(state,month):[]
 const complete=visible.filter(t=>['acceptat','neaplicabil'].includes(state.tasks[t.key]?.status)).length
 const sent=visible.filter(t=>state.tasks[t.key]?.status==='trimis').length
 const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Bucharest'}).format(new Date())
 const overdue=visible.filter(t=>state.tasks[t.key]?.due&&state.tasks[t.key].due!<today&&!['trimis','acceptat','neaplicabil'].includes(state.tasks[t.key].status)).length
 if(compact)return <section style={{...box,marginBottom:24,borderLeft:'4px solid var(--accent)'}}><div style={hint}>RUTINA PROIECTULUI · {complete}/{visible.length} încheiate · {sent} trimise · {overdue} restante</div><h2 style={{fontSize:18,fontWeight:650,margin:'7px 0'}}>{next?`Următorul pas: ${next.title}`:'Documentele sunt trimise sau încheiate'}</h2><p style={hint}>{next?.action||'Verifică răspunsurile și marchează acceptările primite.'}</p><Link href={`/${firmaSlug}/${luna}/obligatii-recurente`} style={{color:'var(--accent)',fontSize:'var(--fs-md)',fontWeight:600}}>Deschide rutina lunii →</Link></section>
 return <section style={{display:'grid',gap:16}}>
 <div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}>
 {!purchaseId&&<button style={tabStyle(tab==='rutina')} aria-pressed={tab==='rutina'} onClick={()=>setTab('rutina')}>✓ Rutina lunii</button>}
 <button style={tabStyle(tab==='formulare')} aria-pressed={tab==='formulare'} onClick={()=>setTab('formulare')}>Formulare și versiuni</button>
 <button style={tabStyle(tab==='setari')} aria-pressed={tab==='setari'} disabled={busy} onClick={()=>void openSettings()}>Date permanente și termene</button>
 <span role="status" style={{...hint,marginLeft:'auto',fontWeight:600,color:busy||autoSaving?'var(--text-secondary)':dirty||settingsDirty?'var(--warning)':'var(--success)'}}>{busy||autoSaving?'Se salvează…':dirty?'Se salvează automat…':settingsDirty?'Setări nesalvate':state.updatedAt?'✓ Salvat automat':''}</span>
 {tab!=='setari'&&<button style={{...button,background:'var(--accent-solid)',color:'#fff'}} disabled={busy||!dirty} onClick={()=>void run(async()=>{await save();setMessage('Modificările au fost salvate.')})}>Salvează modificările</button>}
 </div>
 {err}{message&&<div role="status" style={{...hint,color:'var(--success)'}}>{message}</div>}
 <fieldset disabled={busy} style={{border:0,padding:0,minWidth:0,display:'grid',gap:16}}>
 {tab==='rutina'&&<RutinaLunii state={state} month={month} next={next} onEdit={edit} onUpload={(f,k)=>void upload(f,k)} assetUrl={assetUrl} onRaport={()=>{setKind('raport');setTab('formulare')}}/>}
 {tab==='formulare'&&<>
 <div style={box}><label style={hint}>Alege formularul<select style={{...input,marginTop:5}} value={kind} onChange={e=>setKind(e.target.value as FormKind)}>{Object.entries(FORM_LABELS).filter(([k])=>purchaseId?['oferta','nota','receptie'].includes(k):['raport','restituire'].includes(k)).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{selected?.fields._preluat&&<p style={hint}>Câmpuri preluate din {selected.fields._preluat}. Revizuiește activitățile și personalul pentru perioada curentă.</p>}<p style={{...hint,marginTop:10}}>Se generează un document Word editabil, pe modelul original. Fiecare generare păstrează o versiune separată. Verifică datele înainte de semnare. {purchaseId?'Datele comune despre achiziție sunt preluate automat; produsele pot fi copiate între formulare la cerere.':''}</p></div>
 <div style={box}><h3 style={{fontSize:'var(--fs-lg)',fontWeight:650,marginBottom:12}}>Beneficiar — datele acestui dosar</h3><div style={grid}>{Object.entries(PROFILE_FIELDS).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={state.profile[key]||''} onChange={e=>edit({...state,profile:{...state.profile,[key]:e.target.value}})}/></label>)}</div><p style={{...hint,marginTop:8}}>Datele permanente precompletează dosarele noi. Corecțiile de aici afectează doar acest dosar.</p></div>
 <div style={box}><h3 style={{fontSize:'var(--fs-lg)',fontWeight:650,marginBottom:12}}>{FORM_LABELS[kind]}</h3><div style={grid}>{Object.entries(FORM_FIELDS[kind]).map(([key,label])=><label key={key} style={hint}>{label}<textarea rows={['autorizatii','obiective','activitati','constatari','justificare','personal','personal_vulnerabil'].includes(key)?4:2} style={{...input,resize:'vertical'}} value={selected!.fields[key]||''} onChange={e=>changeDraft({...selected!,fields:{...selected!.fields,[key]:e.target.value}})}/></label>)}</div>
 {purchaseId&&<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{(['oferta','nota','receptie'] as FormKind[]).filter(k=>k!==kind&&state.forms[k]?.lines.length).map(k=><button key={k} style={button} onClick={()=>{if(confirm('Înlocuiești pozițiile acestui formular cu cele din '+FORM_LABELS[k]+'?'))changeDraft({...selected!,lines:structuredClone(state.forms[k].lines)})}}>Preia produse din {FORM_LABELS[k]}</button>)}</div>}
 {['oferta','nota','receptie'].includes(kind)&&<div style={{display:'grid',gap:12,marginTop:20}}><h4 style={{fontSize:'var(--fs-base)',fontWeight:650}}>Produse și servicii — câte o poziție distinctă</h4>{selected!.lines.map((line,index)=><div key={index} style={{...box,padding:12}}><div style={grid}>{Object.entries({supplier:'Furnizor / ofertă',product:'Produs / serviciu',specs:'Specificații tehnice',unit:'UM',qty:'Cantitate',price:'Preț unitar fără TVA',currency:'Monedă',rate:'Curs în lei (1 pentru RON)',source:'Sursă / URL ofertă',date:'Data ofertei'}).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={line[key as keyof typeof line]} onChange={e=>changeDraft({...selected!,lines:selected!.lines.map((x,i)=>i===index?{...x,[key]:e.target.value}:x)})}/></label>)}</div><button style={{...button,marginTop:8}} onClick={()=>changeDraft({...selected!,lines:selected!.lines.filter((_,i)=>i!==index)})}>Elimină poziția {index+1}</button></div>)}<button style={button} onClick={()=>changeDraft({...selected!,lines:[...selected!.lines,emptyLine()]})}>+ Adaugă poziție</button><p style={hint}>Pentru nota de estimare: o poziție pentru fiecare produs din fiecare ofertă. În cerere și recepție păstrează doar produsele necesare; folosește butoanele „Preia produse” pentru a copia lista între formulare.</p></div>}
 <button style={{...button,background:'var(--accent-solid)',color:'#fff',marginTop:18}} onClick={()=>void run(async()=>{const missing=validateDraft(kind,selected!,state.profile);if(missing.length)throw new Error('Completează: '+missing.join('; '));const updated={...state,forms:{...state.forms,[kind]:selected!}};const saved=await save(updated);const data=await response(await fetch('/api/proiect-workflow/document',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope,version:saved!.version,kind})}));setState(data.state);setMessage('Document generat. Îl poți descărca din versiunile de mai jos.')})}>Salvează și generează Word</button>
 </div>
 <div style={box}><h3 style={{fontWeight:650,marginBottom:10}}>Versiuni păstrate — {FORM_LABELS[kind]}</h3>{state.assets.filter(a=>a.task===kind).length===0?<p style={hint}>Nicio versiune încă.</p>:state.assets.filter(a=>a.task===kind).slice().reverse().map(a=><div key={a.id} style={{padding:'8px 0',fontSize:'var(--fs-md)'}}><a style={{color:'var(--accent)'}} href={assetUrl(a.id)}>{a.name} ↓</a><span style={{...hint,marginLeft:10}}>{new Date(a.createdAt).toLocaleString('ro-RO')}</span></div>)}</div>
 </>}
 {tab==='setari'&&settings&&<div style={box}><h3 style={{fontSize:18,fontWeight:650,marginBottom:12}}>Date permanente și reguli pentru dosarele noi</h3><p style={hint}>Modificarea regulilor nu schimbă lunile deja începute. Ziua se calculează în luna de lucru (următoarea perioadei raportate); zilele 29–31 se limitează la ultima zi disponibilă.</p><div style={{...grid,margin:'14px 0'}}>{Object.entries(PROFILE_FIELDS).map(([key,label])=><label key={key} style={hint}>{label}<input style={input} value={settings.profile[key]||''} onChange={e=>{setSettingsDirty(true);setSettings({...settings,profile:{...settings.profile,[key]:e.target.value}})}}/></label>)}</div>
 {TASKS.map(t=>{const r=settings.rules[t.key];return <div key={t.key} style={{...grid,alignItems:'end',padding:'12px 0',borderTop:'1px solid var(--border)'}}><span style={{fontSize:'var(--fs-md)'}}>{t.title}</span><label style={hint}>Frecvență<select style={input} value={r.frequency} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,frequency:e.target.value as typeof r.frequency}}})}}><option value="monthly">Lunar</option><option value="annual">Anual</option><option value="manual">La cerere, fără termen automat</option></select></label><label style={hint}>Ziua (1–31)<input style={input} type="number" min="1" max="31" value={r.day} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,day:Number(e.target.value)}}})}}/></label><label style={hint}>{r.frequency==='annual'?'Luna din an (1–12)':'Decalaj față de luna de lucru'}<input style={input} type="number" min={r.frequency==='annual'?1:0} max={r.frequency==='annual'?12:2} value={r.frequency==='annual'?r.month:r.offset} onChange={e=>{setSettingsDirty(true);setSettings({...settings,rules:{...settings.rules,[t.key]:{...r,[r.frequency==='annual'?'month':'offset']:Number(e.target.value)}}})}}/></label></div>})}
 <div style={{display:'flex',gap:10,marginTop:16,flexWrap:'wrap'}}><button style={button} onClick={()=>void run(async()=>{const data=await response(await fetch('/api/proiect-workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({firmaId,scope:'settings',state:settings})}));setSettings(data.state);setSettingsDirty(false);setMessage('Datele permanente și termenele pentru dosarele noi au fost salvate.')})}>Salvează regulile permanente</button><button style={button} onClick={()=>{edit({...state,profile:{...settings.profile}});setTab('formulare')}}>Preia datele permanente în acest dosar</button>{!purchaseId&&<button style={button} onClick={()=>{if(confirm('Recalculezi toate termenele acestei luni după regulile afișate?')){edit({...state,rules:settings.rules,tasks:Object.fromEntries(Object.entries(state.tasks).map(([key,row])=>[key,{...row,due:dueDate(month,settings.rules[key])}]))});setTab('rutina')}}}>Aplică regulile și acestei luni</button>}</div>
 </div>}
 </fieldset>
 </section>
}
