// Crescut manual la fiecare modificare livrata, ca reper vizual ca update-ul a ajuns live.
// Fiecare intrare descrie pe scurt ce s-a schimbat - click pe "Update N" (jos-stanga) arata istoricul.
export interface UpdateEntry { v: number; text: string }

export const UPDATES: UpdateEntry[] = [
  { v: 86, text: 'Inbox Facturi: sincronizarea Gmail scanează până la 100 de emailuri cu PDF, paginat, ca să prindă facturile din august precum ISO/Verk/Skoutz chiar dacă sunt mai jos în inbox' },
  { v: 85, text: 'Inbox Facturi: sincronizarea Gmail pornește ca job în fundal; poți pleca de pe pagină, iar statusul și rezultatele se recuperează când revii' },
  { v: 84, text: 'Inbox Facturi: sincronizarea Gmail nu mai importă PDF-uri fără legătură cu firmele; furnizorii externi rămân acceptați dacă firma apare ca beneficiar/cumpărător' },
  { v: 83, text: 'Inbox Facturi: sincronizarea Gmail caută mereu facturi din 01 ale lunii contabile precedente până în prezent, în funcție de luna de lucru deschisă' },
  { v: 82, text: 'Inbox Facturi: Gmail conectat poate fi sincronizat manual; aplicația citește emailuri recente cu atașamente PDF, importă facturile prin AI, detectează firma și marchează duplicatele' },
  { v: 81, text: 'Inbox Facturi: Gmail 1 și Gmail 2 pot porni conectarea reală prin Google OAuth; callback-ul salvează token-ul securizat pe firmă și pe sursa selectată' },
  { v: 80, text: 'Inbox Facturi: cardurile Gmail 1, Gmail 2, iCloud și Oblio au acum buton Conectează/Configurează și salvează sursa pe firmă în inbox_surse_email' },
  { v: 79, text: 'Inbox Facturi: cardul Oblio apare lângă Gmail 1, Gmail 2 și iCloud, pregătit pentru conectare prin API token și preluare facturi/e-Factura' },
  { v: 78, text: 'Luna de lucru este afișată separat de perioada contabilă: pentru luna de lucru Septembrie apare „Contabilitate 1-31 August 2026 (lucrat în Septembrie 2026)”, iar luna următoare va afișa perioada contabilă următoare' },
  { v: 77, text: 'Facturi restante: lista afișează număr factură, furnizor, dată și sumă; când o factură este asociată în Extras de cont, factura restantă potrivită se marchează automat ca achitată' },
  { v: 76, text: 'Nou: modul Inbox Facturi pe fiecare firmă reală — documentele primite din email/Oblio pot fi încărcate în lot, AI detectează firma după CIF/nume, verifică duplicatele și le salvează la firma/luna potrivită' },
  { v: 75, text: 'Extras de cont: tranzacțiile rămân în ordinea extrasului după atașarea documentelor; lista nu mai mută automat rezolvatele la final, deci workspace-ul nu mai sare între poziții' },
  { v: 74, text: 'Extras de cont: poți selecta și încărca mai multe facturi pe aceeași tranzacție/comandă; documentele rămân grupate pe tranzacția bancară și sunt afișate cu referința comenzii' },
  { v: 73, text: 'Extras de cont: ce scrii în tab-ul Note rămâne păstrat local când schimbi tab-ul și revii, dar se resetează normal la refresh de pagină' },
  { v: 72, text: 'Extras de cont: după atașarea unui document, workspace-ul trece la tranzacția imediat următoare după ID-ul tranzacției curente, fără salturi peste 2-3 poziții când lista se reordonează' },
  { v: 71, text: 'Extras de cont: referința internă afișată și copiată în workspace-ul tranzacției este scurtată la numărul util introdus manual, de exemplu 435138 în loc de 435138;261' },
  { v: 70, text: 'Publicare: update-ul pentru importul AI de extrase pe monede separate a fost împins la deploy și apare în istoricul din stânga jos' },
  { v: 69, text: 'Extras de cont: fallback suplimentar la citirea AI - dacă AI întoarce o singură listă mixtă de tranzacții, sistemul o separă local pe valute înainte de salvare (RON/EUR etc.)' },
  { v: 68, text: 'Extras de cont: butonul „Citire extras cu AI” împarte automat un PDF cu mai multe conturi/monede în extrase separate, de exemplu RON și EUR, fiecare cu tranzacțiile proprii' },
  { v: 67, text: 'Extras de cont: importul PDF acceptă acum și răspunsul AI cu structură pe conturi (`conturi: [...]`), iar dacă un PDF EUR/HUF/RON este pus pe cardul greșit apare mesaj clar cu moneda detectată' },
  { v: 66, text: 'Extras de cont: ABXHOMES SRL are acum cod de deblocare PDF 51569342 cu buton Copy, lângă codul deja adăugat pentru AB HOMES INVEST' },
  { v: 65, text: 'eMAG: avizele BG se calculează/afișează în EUR, HU în HUF, RO în RON; task-urile și contorul modulului se actualizează singure după încărcarea facturilor. Extras AB HOMES INVEST are cod de deblocare PDF cu Copy, iar Dispozițiile de plată au verificare duplicate și afișează luna/data facturii' },
  { v: 64, text: 'Fix: pagina de Note pe tranzacții (din Extras de cont) e acum inclusă și în „PDF toate"/„ZIP categorii" — nu mai rămâne doar în aplicație, ajunge și la contabilitate o dată cu restul documentelor. Verificate toate cele 49 de pagini de modul din toate firmele, fără erori' },
  { v: 63, text: 'Nou: „Recomandări pentru sistem" la finalul hub-ului lunar — la cerere, AI analizează task-uri, module dezactivate, tranzacții nedocumentate și restanțe reale ale lunii și propune 3-5 îmbunătățiri concrete pentru mai puțină muncă manuală pe viitor (necesită rularea migrării SQL recomandari_luna)' },
  { v: 62, text: 'Rafinare vizuală completă: font Inter peste tot, paletă nouă pe toate cele 3 teme (Light alb pe gri, Night grafit nu negru pur), culoare cu sens (albastru=acțiune, verde=gata, amber=în lucru, roșu=restanțe) în loc de culoarea firmei peste tot, task-uri ca bifă+text în loc de pastile, Glass revenit la doar sidebar/header/dropdown-uri' },
  { v: 61, text: 'Glass rescris alb/translucent (nu întunecat) și extins pe carduri, rânduri de modul și tab-uri, nu doar sidebar/header. Conținutul paginilor folosește acum mult mai mult din lățimea ecranului (820-1000px → 1200-1500px)' },
  { v: 60, text: 'Sistem global de aparență: Sistem/Deschis/Întunecat/Glass, selector în sidebar (vizibil pe orice pagină), persistat, fără clipire la încărcare. Glass e translucent+blur doar pe sidebar/header/dropdown-uri — tabelele și formularele rămân opace pentru lizibilitate' },
  { v: 59, text: 'Hub-ul lunar: module lunare din carduri mari (230px+) în rânduri compacte (~70-100px) — toate modulele unei firme încap acum pe un singur ecran, fără scroll; corectat și overflow orizontal pe mobil în antetul hub-ului' },
  { v: 58, text: 'Extras de cont: eliminat mini-sidebar-ul propriu (logo + căutare duplicate) rămas dintr-o versiune veche, dinainte de shell-ul persistent — bara de progres și butonul de finalizare extras au fost mutate în conținutul principal' },
  { v: 57, text: 'Dashboard: facturi restante vizibile direct pe fiecare card de firmă + total pe prima linie, fără să intri în firmă' },
  { v: 56, text: 'Performanță: comutatorul de lună de la Raport lunar (proiect) precarcă acum luna vecină + căutarea globală de documente nu mai poate afișa un răspuns vechi peste unul nou la tastare rapidă + Extras de cont face 2 interogări în paralel în loc de secvențial' },
  { v: 55, text: 'Shell persistent pe toată aplicația: sidebar-ul nu se mai reconstruiește nici la Dashboard/Furnizori/Date personale/Model documente/Facturi de asociat (nu doar în interiorul unei firme+luni) + comutator rapid de firmă în capul paginii, cu prefetch' },
  { v: 54, text: 'Raport lunar (proiect): redesign complet — workspace cu previzualizare + editor pe secțiuni (nu textarea-uri), liste editabile individual, dată-interval, autosave, tab-uri (Editare/Previzualizare/Istoric/Fișier); arhitectură generică, reutilizabilă pentru viitoare tipuri de documente' },
  { v: 53, text: 'Raport lunar (proiect): buton de ștergere pentru câmpurile personalizate (textul revine fix, cu valoarea curentă) + indicii vizuale mai clare pentru selecție și generare' },
  { v: 52, text: 'Raport lunar (proiect): poți selecta orice text din previzualizare și să-l faci "câmp editabil" cu propria etichetă, pe lângă cele 4 fixe' },
  { v: 51, text: 'Raport lunar (proiect): antetul/subsolul cu sigle apar acum la dimensiunea corectă din Word, aliniate pe orizontală, nu uriașe/stivuite' },
  { v: 50, text: 'Previzualizare Word direct în pagină la Raport lunar (proiect), randată în aplicație, fără server extern' },
  { v: 49, text: 'Viteză: schele de încărcare instant pe toate paginile + module lunare încărcate lazy (cod separat per modul)' },
  { v: 48, text: 'Nou: tab PROIECT AB Textile, cu Raport lunar — document Word unic, se înlocuiește la reîncărcare, nu se acumulează' },
  { v: 47, text: 'Layout comun pentru firmă+lună — sidebar-ul nu se mai reconstruiește la fiecare navigare între module' },
  { v: 46, text: '5StarDesk: reparat bug de extragere AI care dubla o rezervare din borderou + verificare inversă (facturi fără rezervare)' },
  { v: 45, text: 'Navigare mai rapidă: interogări paralelizate pe Furnizori, Date personale, Model documente, Facturi de asociat, hub-ul lunii' },
  { v: 44, text: 'Dashboard: Date firmă afișat direct la fiecare firmă, fără click' },
]

export const APP_UPDATE = UPDATES[0].v
